# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20171122_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='consumed',
            field=models.TextField(blank=True, verbose_name='Consumed'),
        ),
    ]
