# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-30 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_mealitem_consumed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealitem',
            old_name='ingredient',
            new_name='ingredien',
        ),
    ]
