# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-30 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_auto_20171130_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealitem',
            old_name='ingredien',
            new_name='ingredient',
        ),
    ]
