# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-04 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
        ('nutrition', '0005_auto_20171130_1308'),
    ]

    operations = [
    ]
