# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-07 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_merge'),
        ('nutrition', '0004_mealitem_time'),
        ('nutrition', '0004_merge'),
    ]

    operations = [
    ]
