# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.5
        environment:
          - TEST_MOBILE=True  DB=postgresql TRAVIS_NODE_VERSION="4"
          - TEST_MOBILE=True  DB=sqlite     TRAVIS_NODE_VERSION="4"
          - TEST_MOBILE=False DB=postgresql TRAVIS_NODE_VERSION="4"
          - TEST_MOBILE=False DB=sqlite     TRAVIS_NODE_VERSION="4"

      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/wg-a-team/wger
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv-django
            . venv-django/bin/activate
            pip install -r requirements_devel.txt
            pip install wger
            # npm install
            if [[ "$DB" = "postgresql" ]]; then pip install psycopg2; fi

            # Setup application
            if [[ "$DB" = "sqlite" ]]; then wger create_settings; fi
            if [[ "$DB" = "postgresql" ]]; then wger create_settings --database-type postgresql; fi
            
      - save_cache:
          paths:
            - ./venv-django
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv-django/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports