# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.13 on 2017-11-27 14:32
=======
# Generated by Django 1.9.13 on 2017-11-27 10:12
>>>>>>> develop
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20171122_0904'),
<<<<<<< HEAD
        ('email', '0002_auto_20171126_0811'),
=======
        ('email', '0002_auto_20171121_2207'),
>>>>>>> develop
    ]

    operations = [
    ]
