# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20171122_0904'),
        ('email', '0002_auto_20171126_0811'),
    ]

    operations = [
    ]
