# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20171121_2207'),
        ('gym', '0007_auto_20171122_0904'),
    ]

    operations = [
    ]
