# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171126_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_user',
            field=models.BooleanField(default=False),
        ),
    ]
