# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171126_0839'),
        ('core', '0010_auto_20171122_0904'),
    ]

    operations = [
    ]
