# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge'),
        ('core', '0011_merge'),
    ]

    operations = [
    ]
