# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-01 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_workoutlog_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='session_id',
        ),
    ]
