# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20171121_2207'),
        ('manager', '0009_merge'),
    ]

    operations = [
    ]
