# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_workoutlog_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutSession', verbose_name='Session id'),
        ),
    ]
