# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-06 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge'),
        ('manager', '0011_workoutlog_session_id'),
    ]

    operations = [
    ]
