# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-07 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_merge'),
        ('manager', '0010_merge'),
    ]

    operations = [
    ]
